F 2
champl0o/db-rails pull request #3
Opened 2021-10-22 15:25 UTC by champl0o

2021-10-23 07:21 UTC, flvrone requested changes
Live and learn

2021-10-23 07:21 UTC, flvrone commented on app/models/city.rb
> +  end
Good SQL, but better way to do it in rails is this:
```has_many :items, through: :users```

2021-10-23 07:21 UTC, flvrone commented on app/models/user.rb
> +    bookings.where('item_id = ?', item.id) ? true : false
This is a bug, and it will always return true :)
Here's what would work:
```ruby
bookings.where(item: item).exists?
```

2021-10-23 07:21 UTC, flvrone commented on app/models/user.rb
> +    items.where('owner_id = ?', owner.id) ? true : false
Same, a bug

2021-10-23 07:21 UTC, flvrone commented on app/models/user.rb
> +  def items
Whoops, now you override your `has_many :items` association method, now it is broken. 💔

2021-10-23 07:21 UTC, flvrone commented on app/models/user.rb
> +    Item.joins("INNER JOIN bookings ON bookings.user_id = items.owner_id WHERE bookings.user_id = #{id}")
This is another case for association, it can be done better like this:
```ruby
has_many :booked_items, through: :bookings, ...
```

2021-10-23 07:21 UTC, flvrone commented on db/seeds/02_users.rb
> +City.all.each do |i|
This `i` is in fact a city object :)

2021-10-23 07:21 UTC, flvrone commented on db/seeds/02_users.rb
> +    city: City.last
And this is strange, is this your intention?

2021-10-23 07:21 UTC, flvrone commented on db/seeds/05_reviews.rb
> +User.all.each do |_user|
Didn't you find it strange you don't need a user here? :)

2021-10-23 07:21 UTC, flvrone commented on spec/models/user_spec.rb
>      it { is_expected.to have_many(:items).with_foreign_key('owner_id') }
It is a shame this spec didn't catch that the association is now broken :(

2021-10-23 07:21 UTC, flvrone commented on spec/models/user_spec.rb
> +    it 'should return true if item belongs to user bookings' do
And it never returns `false` huh

2021-10-23 07:21 UTC, flvrone commented on spec/models/user_spec.rb
> +      expect(user).to receive(:item_reviewable?).with(item).and_return(true)
This is faking the results, it will never call your real method, do not use it, until you know what it's for.

2021-10-23 07:21 UTC, flvrone commented on spec/models/user_spec.rb
> +      expect(result).to be_truthy
```ruby
expect(user.item_reviewable?).to be true
```
Also please read https://betterspecs.org/

2021-11-14 12:34 UTC, champl0o commented on app/models/user.rb
> +  def items
oh my god
forgot about the has many association

2021-11-14 12:40 UTC, champl0o commented on db/seeds/05_reviews.rb
> +User.all.each do |_user|
Changed to items

2022-09-22 21:54 UTC, champl0o commented on db/seeds/05_reviews.rb
> +  reviewable: Item.last
for now, I seed just items here, don't see need to add reviews for users

2022-09-22 22:05 UTC, champl0o commented on spec/factories/items.rb
> +    end
there was a problem with the creating owner using this factory. Let me explain
<img width="463" alt="image" src="https://user-images.githubusercontent.com/51294189/191859273-9be3f0be-10b4-4c0f-a83d-edccf06314fe.png">
<img width="189" alt="image" src="https://user-images.githubusercontent.com/51294189/191859657-03676f05-794b-4a69-ad97-ac38cb72d765.png">

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/51294189/191859624-e0544ce8-cb56-4dd2-bf1b-af509a0240de.png">

the owner association in the `item` was generated not with our owner, which was created in the let statement, so I investigated and found out that `trait` would help me with this problem

2023-12-26 21:54 UTC, closed without merging